// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7VUTcsrab-cK4qCXL_CoRSjale6Z51LM',
    appId: '1:535737708809:web:88143ff77d92c936aae3d8',
    messagingSenderId: '535737708809',
    projectId: 'precious-salon',
    authDomain: 'precious-salon.firebaseapp.com',
    databaseURL: 'https://precious-salon-default-rtdb.firebaseio.com',
    storageBucket: 'precious-salon.appspot.com',
    measurementId: 'G-P6KXC8MF6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPy1jT-UN9JhXTZvCTAmHWDaN6YVX1MNg',
    appId: '1:535737708809:android:050fe0b989e35f27aae3d8',
    messagingSenderId: '535737708809',
    projectId: 'precious-salon',
    databaseURL: 'https://precious-salon-default-rtdb.firebaseio.com',
    storageBucket: 'precious-salon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC70d51idTlzErObmaaBB8QuTwseJNCIeE',
    appId: '1:535737708809:ios:1a509a2d144a161caae3d8',
    messagingSenderId: '535737708809',
    projectId: 'precious-salon',
    databaseURL: 'https://precious-salon-default-rtdb.firebaseio.com',
    storageBucket: 'precious-salon.appspot.com',
    iosClientId: '535737708809-2ekndet0sejnnl8g5isplvh5qm6c2inj.apps.googleusercontent.com',
    iosBundleId: 'com.example.preciousHairSalon',
  );
}
